name: naija_charades
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  flip_card: ^0.4.4
  auto_size_text: ^2.1.0
  animated_text_kit: ^2.2.0
  flutter_icons: ^1.1.0
  sensors: ^0.4.2+2
  tilt_action: ^0.1.0
  provider: ^4.1.3
  video_player: ^0.10.11+2
  gallery_saver: ^2.0.1
  camera: ^0.5.8+2
  path_provider: ^1.6.11
  flushbar: ^1.10.4
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:

  uses-material-design: true

  assets:
    - assets/logo.jpg
